INSERT INTO TB_CHAVE (DESC,LOCAL,NUM) VALUES ('Não esquecer o ar condicionado ligado','Laboratório',1);
INSERT INTO TB_CHAVE (DESC,LOCAL,NUM) VALUES ('Macaneçata Quebrada','Sala',1);
INSERT INTO TB_CHAVE (DESC,LOCAL,NUM) VALUES ('','Sala',2);
INSERT INTO TB_CHAVE (DESC,LOCAL,NUM) VALUES ('Computadores do fundo não funcionam','Laboratório',2);
INSERT INTO TB_CHAVE (DESC,LOCAL,NUM) VALUES ('','Laboratório',3);
INSERT INTO TB_CHAVE (DESC,LOCAL,NUM) VALUES ('Ar condicionado não funciona','Laboratório',4);


INSERT INTO TB_MOVIMENTACAO (ID_CHAVE,PESSOA,DATA_EMPRESTIMO,DATA_DEVOLUCAO) VALUES (1,'Rafael','20/10/2022','');
INSERT INTO TB_MOVIMENTACAO (ID_CHAVE,PESSOA,DATA_EMPRESTIMO,DATA_DEVOLUCAO) VALUES (2,'Cláudio','15/10/2022','18/10/2022');



